project:
  type: website
  output-dir: _site
  resources:
    - CNAME

website:
  title: "How To Train Your Researcher"
  site-url: https://httyr.com
  description: "Open-source advice for entering AI research."
  navbar:
    left:
      - href: EROP/index.qmd
        text: EROP
      - href: advice/reading_advice.qmd
        text: Reading Advice
      - href: advice/writing_advice.qmd
        text: Writing Advice
      - href: advice/lone_ranger.qmd
        text: The Lone Ranger
  sidebar:
    - title: "EROP 2026 (June)"
      style: docked
      contents:
        - EROP/index.qmd
        - EROP/research-brief.qmd
        - section: "Daily Plan"
          contents:
            - EROP/day-1.qmd
            - EROP/day-2.qmd
            - EROP/day-3.qmd
            - EROP/day-4.qmd
            - EROP/day-5.qmd
        - EROP/mentoring-strategy.qmd
  repo-url: https://github.com/How-To-Train-Your-Researcher/HTTYR
  repo-actions: [edit, issue]

language:
  title-block-published: "Updated"
  title-block-author-single: "Authors"
  title-block-author-plural: "Authors"

bibliography: references.bib
csl: https://www.zotero.org/styles/ieee

format:
  html:
    theme: Cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    css: styles.css

editor:
  render-on-save: true