---
title: "How To Train Your Researcher (HTTYR)"
authors: "Yuriel Ryan"
date: last-modified
---

# Introduction

Hello! This site was created by a group of graduate students and researchers from Singapore to collate practical (and hopefully helpful) advice to do AI/ML research. This documentation is intended for new researchers or for those interested in starting their AI research journey. The goal is simply to reduce the amount of friction a budding researcher might encounter as they start out on this new venture.

This is also the homepage for [SYAI Lab: Early Research Opportunity Program (EROP)](https://sgyouthai.org/programs#Labs) organized by [Singapore Youth AI](https://sgyouthai.org/) and supported by [AI Singapore](https://aisingapore.org/).

::: {.callout-note}
This page is maintained on a voluntary basis by a group of researchers. If you would like to contribute or raise an issue, kindly do so [here](https://github.com/How-To-Train-Your-Researcher/HTTYR)!
:::

---

## Resources

- [Reading Advice](advice/reading_advice.qmd) — advice on reading research papers
- [Writing Advice](advice/writing_advice.qmd) — advice on academic writing
- [The Lone Ranger](advice/lone_ranger.qmd) — advice for when you are the only subject matter expert
- [EROP Playbook](EROP/index.qmd) — the Early Research Opportunity Program curriculum

---

## Contributors
This page was made possible from the contributions of the people below. In no particular order, the humans that made direct contributions:

- [Yuriel Ryan](https://yurielryan.github.io/){target="_blank"}
- [Nicole Oo](https://www.linkedin.com/in/nicole-oo-hy/){target="_blank"}
- [Clyde Lhui](https://www.linkedin.com/in/clydelhui/){target="_blank"}
- [Russell Tan](https://russelltankm.com/){target="_blank"}
- [Zi-Yu Khoo](https://www.linkedin.com/in/zi-yu-khoo/){target="_blank"}

**Advisors**
In no particular order, the advisors that provided helpful guidance/insights for the aformentioned humans:

- [Prof. Roy Lee](https://www.roylee.sg/){target="_blank"}
- [Prof. Min Hun Lee](){target="_blank"}
- [Adriel Kuek](https://www.linkedin.com/in/adrielkuek/){target="_blank"}

